name: Docker

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build & Push Marketing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: registry.jkrumm.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/marketing/Dockerfile
          push: true
          tags: |
            registry.jkrumm.com/basalt-ui-marketing:latest
            registry.jkrumm.com/basalt-ui-marketing:${{ github.sha }}
          cache-from: type=gha,scope=marketing
          cache-to: type=gha,mode=max,scope=marketing
